version: "3"
services:
  app:
    container_name: "fireplace"
    restart: always
    environment:
      - access_token=$access_token
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        accesstoken: "${GITHUB_TOKEN}"
    ports:
      - "0.0.0.0:8999:8999"
    depends_on:
      - mongo
    networks:
      - network-fireplace
    environment:
      - FIREPLACE_DATABASE_URL=mongodb://mongo:27017
      - FIREPLACE_SERVER_LOGLEVEL=info
  mongo:
    container_name: mongo-fireplace
    image: mongo
    volumes:
      - "./data:/data/db"
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - network-fireplace
networks:
  network-fireplace:
    driver: bridge

