version: "3"

services:
  fireplace:
    container_name: "fireplace"
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "0.0.0.0:8999:8999"
    depends_on:
      - mongo
    networks:
      - fireplace
    env_file:
      - ./.env
  mongo:
    container_name: mongo-fireplace
    image: mongo:bionic
    volumes:
      - mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - fireplace

volumes:
  mongo:

networks:
  fireplace:
    driver: bridge

